### ISSUE TITLE
Recent changes cause Mailpile to crash when starting

### ISSUE THREAD

**Issue by bnvk** [mailpile/Mailpile#1425]
In my eagerness to see the boatload of updates you just pushed, I merged them in. Now when running Mailpile it just crashes!

```
[user@mailpile Mailpile]$ ./mp
Failed to load language C                                                      
Failed to configure i18n. Using fallback.                                      
Failed to decrypt configuration, please log in!                                
Elapsed: 0.002s (quit: Shutting down...)                                       
Traceback (most recent call last):
  File "/home/user/Mailpile/mailpile/commands.py", line 589, in _run_sync
    return self._finishing(command(self, *args, **kwargs))
  File "/home/user/Mailpile/mailpile/commands.py", line 587, in command
    return self.command(*args, **kwargs)
  File "/home/user/Mailpile/mailpile/commands.py", line 2786, in command
    time.sleep(2)
KeyboardInterrupt

help/splash error: Failed: help/splash 
Error
Elapsed: 1.131s (interact: Ran interactive shell)
Waiting for <HttpWorker(Thread-3, started daemon 140252773512960)>
Waiting for <DumbWorker(Dumb worker, initial)>: Idle (1s, jobs=0, jobs_after=0)
All stopped!
Elapsed: 0.000s (ps: Listed events, threads, and locks)
Recent events:
  Nothing Found

Events in progress:
  Nothing Found

Live sessions:
  Z69Eih8fJQh2bFvaW87mnkPvqeHd3h3J/{'t': '561abce9'} = GUI plugin client (1s)

Postinglist timers:
{'load': 0, 'load_count': 0, 'save': 0, 'save_count': 0, 'render': 0}

Threads: (bg delay 0.000s, live=0, httpd=0)
  <HttpWorker(Thread-3, started daemon 140252773512960)>
  <_MainThread(MainThread, started 140253048350464)>

Locks:
  config._lock is unlocked
  mailpile.plugins.compose.GLOBAL_EDITING_LOCK is unlocked
  mailpile.plugins.contacts.GLOBAL_VCARD_LOCK is unlocked
  mailpile.postinglist.GLOBAL_GPL_LOCK is unlocked
  mailpile.postinglist.GLOBAL_OPTIMIZE_LOCK is unlocked
  mailpile.postinglist.GLOBAL_POSTING_LOCK is unlocked
[user@mailpile Mailpile]$ 
```

**Comment by BjarniRunar** [comment]
This has not been the case for myself or at least 3 others who have pulled this down and tested it... so more details are needed to verify this.

1. Is your source tree clean?
2. Why does that stack-trace say you hit CTRL+C ? :)

**Comment by bnvk** [comment]
> 1. Is your source tree clean?

Yes. To be certain, I did a fresh clone and the crash happens with almost identical errors printing out. However, upon re-cloning, now I'm at least seeing the auth screen render before the backend dies.

> 2. Why does that stack-trace say you hit CTRL+C ? :)

I'm not touching the keyboard. I'm just typing `./mp` like usual and then it does it's startup thing, but then quickly fails in less than 3 seconds. This instance and error is happening in Fedora 21 in my VM that I've been successfully running Mailpile from for the last two weeks.

However, I just tried this in a fresh Debian 8 VM. This also crashes, but is showing the "Welcome to Mailpile" setup screen. Here's the CLI error

```
user@tahoe:~/Mailpile$ ./mp
Failed to configure i18n. Using fallback.                                      
Metadata index not found: /home/user/.local/share/Mailpile/default/mailpile.idx
Elapsed: 0.035s (Loaded metadata, 0 messages)                                  
Metadata index not found: /home/user/.local/share/Mailpile/default/mailpile.idx
Elapsed: 0.000s (load: Loaded metadata index)
Elapsed: 0.001s (quit: Shutting down...)                                       
Traceback (most recent call last):
help/splash error: Failed: help/splash 
Erroreturn self._finishing(command(self, *args, **kwargs))
Elapsed: 1.144s (interact: Ran interactive shell)
user@tahoe:~/Mailpile$  
  File "/home/user/Mailpile/mailpile/commands.py", line 2786, in command
    time.sleep(2)
KeyboardInterrupt
```

What's odd here is that KeyboardInterupt bit is actually printing after the bash line where my cursor is flashing.

**Comment by axeltomasson** [comment]
Hi guys,

I am also getting this one and can confirm I am not pressing ctrl+c.

The browser opens up the login screen and then ./mp dies automagically.

I am running an "unsupported" setup.  FreeBSD 10.2.

Clean source tree.

Cheers,
Axel

**Comment by BjarniRunar** [comment]
OK, weird. This might be caused by a plug-in that I didn't have enabled at my end, and so was untested. Do either of you remember whether you had any plugins active?

**Comment by axeltomasson** [comment]
No active plugins.
Have MAILPILE_HOME set to an alternate location.
And same thing happens when I use the default location with empty .local/share/Mailpile.
Is there any way to force debug on without the interactive shell?

**Comment by BjarniRunar** [comment]
Woops, didn't meant to close. I've made a small change based on a hunch... can you pull and re-test?

**Comment by BjarniRunar** [comment]
I think I know what's going on. :-)  You guys probably have Python webkit module installed, so a half-baked webkit native GUI was trying to launch and probably failing in some way that caused things to crash and burn. I've pushed up a change to prefer the external browser by default, which may avoid the problem - if not let me know and I'll dig deeper.

**Comment by bnvk** [comment]
@BjarniRunar sounds probably about Python webkit. Thanks for debugging a bit. I confirm I didn't have any plugins enabled in either my Debian or Fedora instance. I pulled your updates, but it still crashing in the same way!

**Comment by ClashTheBunny** [comment]
Still broken on e52c3cd239d849106fccab2ac144701f972166aa for me, reverted to 49c61e1aa23b2894dba6f806f36f7aae2092da80 and it is functioning.

**Comment by BjarniRunar** [comment]
This should be fixed, I just disabled the UI for now.
